//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumaneSociety
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adopter
    {
        public int ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string User_Address { get; set; }
        public string Contact_Number { get; set; }
        public string Pet_Preference { get; set; }
        public string User_Bio { get; set; }
    }
}
